name: "Daily dose."
description: "A photo a day project."
author: "Chris Porter"
url: "http://christopherporter.co.uk/daily-dose"
future: false
exclude: [README.md, Rakefile, node_modules, .editorconfig, .gitattributes, .gitignore]
permalink: :title